---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: www/content/posts
  label: Posts
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: document
  path: www/content/authors/authors.yml
  label: Authors
upload_dir: www/static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
